name: appcoba

description: Sample Vania backend web application framework
version: 1.0.0

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  vania: ^0.6.2
  intl : ^0.18.0
  bcrypt: ^1.1.3
  crypto: ^3.0.6
  dart_jsonwebtoken: ^2.14.1
  eloquent: ^3.2.1
  mailer: ^6.2.0
  meta: ^1.16.0
  mime: ^1.0.6
  path: ^1.9.1
  sprintf: ^7.0.0
  string_scanner: ^1.4.0
  uuid: ^4.5.1

  


dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  http: ^1.2.2
  http_parser: ^4.1.1
  build_runner: ^2.4.13
  mockito: ^5.4.4

dependency_overrides:
  pointycastle: 3.7.3